### ISSUE TITLE
请教一下作者

### ISSUE THREAD

**Issue by Vensent** [JailedBird/ArouterKspCompiler#10]
首先感慨一下你好厉害啊。

我们项目很不巧的是用了美团的WMRouter的方案，但是真的这里编译的时间太长了，我找了一圈没有发现WMRouter的Ksp Compiler，所以我想问问你是怎么来改写ARouter的，有没有一些学习的文档或者教程，因为这个转换的过程真的太难了。我对着你的代码思路看了下改美团的还是有点搞不定。

**Comment by Vensent** [comment]
太感谢了！马上star一下，然后慢慢学习一下！

**Comment by Vensent** [comment]
https://www.yuque.com/jailedbird/gbmyp7/bs5t6e5zthrgfaua?singleDoc# 《KSP注解处理器分享》

对了，这个网站好像打不开啊。

**Comment by JailedBird** [comment]
直接打开这个？ https://www.yuque.com/jailedbird/gbmyp7/bs5t6e5zthrgfaua?singleDoc#  应该没问题才对；

**Comment by Vensent** [comment]
应该是OK的，我们公司把这个网址墙了。。
