### ISSUE TITLE
为什么会有kotlin1.7.22这个版本

### ISSUE THREAD

**Issue by kouhengsheng** [JailedBird/ArouterKspCompiler#11]
我在kotlin官网上看到只有kotlin1.7.21这个版本，没有1.7.22这个版本啊，我自己项目里用的也是1.7.21

**Comment by JailedBird** [comment]
是有kotlin1.7.22这个版本的喔；https://github.com/google/ksp/releases/tag/1.7.22-1.0.8

你项目kotlin 1.7.21你用arouterkspcompiler 1.7.20-xxx 应该也没问题的；
