### ISSUE TITLE
Type in a class literal must not be nullable

### ISSUE THREAD

**Issue by codejoyfun** [JailedBird/ArouterKspCompiler#13]
![image](https://github.com/JailedBird/ArouterKspCompiler/assets/43105870/1dd75d49-933a-4ca2-a2e4-0da64e6a4fba)

**Comment by JailedBird** [comment]
你好，可以发一下相关的几个原始文件的关键信息么？

**Comment by codejoyfun** [comment]
> 定位到原因了，navigation应该传递Class类，我搞成了待泛型的了；修复中
![image](https://github.com/JailedBird/ArouterKspCompiler/assets/43105870/7ccbc260-1aa3-4289-9ac2-0848445f6723)

赞
我是这样声明的：
    @Autowired
    @JvmField
    var deviceManagerService: DeviceMgrService? = null

**Comment by JailedBird** [comment]
FIx：AutowiredSymbolProcessorProvider
![image](https://github.com/JailedBird/ArouterKspCompiler/assets/113177053/ec4eb0dc-628d-42fe-8c13-c36333cd5b23)

![image](https://github.com/JailedBird/ArouterKspCompiler/assets/113177053/4c0492cd-0784-4244-a4b5-e7f2903e2b46)

Test case：SecondActivtiy

```
    @Autowired
    lateinit var iProvider1: TestServiceImpl

    @Autowired
    var iProvider2: TestServiceImpl? = null

    @Autowired
    lateinit var iProvider3: TestServiceImplGene<Int>

    @Autowired
    var iProvider4: TestServiceImplGene<Int>? = null

    @Autowired(name = "iProvider5")
    lateinit var iProvider5: TestServiceImpl

    @Autowired(name = "iProvider6")
    var iProvider6: TestServiceImpl? = null

    @Autowired(name = "iProvider7")
    lateinit var iProvider7: TestServiceImplGene<Int>

    @Autowired(name = "iProvider8")
    var iProvider8: TestServiceImplGene<Int>? = null
```

```
@Route(path = "/test/service")
class TestServiceImpl: ITestService1, ITestService2 {
  override fun init(context: Context) {
  }
}

@Route(path = "/test/service")
class TestServiceImplGene<T> : ITestService1, ITestService2 {
  override fun init(context: Context) {
  }
}
```

Result:

```
    substitute.iProvider1 = ARouter.getInstance().navigation(TestServiceImpl::class.java) as
        TestServiceImpl
    substitute.iProvider2 = ARouter.getInstance().navigation(TestServiceImpl::class.java) as
        TestServiceImpl?
    substitute.iProvider3 = ARouter.getInstance().navigation(TestServiceImplGene::class.java) as
        TestServiceImplGene<Int>
    substitute.iProvider4 = ARouter.getInstance().navigation(TestServiceImplGene::class.java) as
        TestServiceImplGene<Int>?
    substitute.iProvider5 = ARouter.getInstance().build("iProvider5").navigation() as
        TestServiceImpl
    substitute.iProvider6 = ARouter.getInstance().build("iProvider6").navigation() as
        TestServiceImpl?
    substitute.iProvider7 = ARouter.getInstance().build("iProvider7").navigation() as
        TestServiceImplGene<Int>
    substitute.iProvider8 = ARouter.getInstance().build("iProvider8").navigation() as
        TestServiceImplGene<Int>?
```

**Comment by JailedBird** [comment]
晚点发布；

**Comment by JailedBird** [comment]
> > 先用这个 com.github.JailedBird:ArouterKspCompiler:bugfix-IPorvider-inject-SNAPSHOT 版本验证下哈；正式版晚点发；
> 
> ![image](https://user-images.githubusercontent.com/43105870/276893015-b713a28e-ab4e-4333-848b-1e0fee875aae.png) ![image](https://user-images.githubusercontent.com/43105870/276895806-fee6aac7-8ff5-4409-bcd4-10960328bbee.png) ![image](https://user-images.githubusercontent.com/43105870/276895845-1956708f-e91e-42c7-916e-f68b35ac6d37.png)

上个版本存在这个问题么？

**Comment by JailedBird** [comment]
多谢反馈 又打一个补丁🤣
![image](https://github.com/JailedBird/ArouterKspCompiler/assets/113177053/e4ad0515-8a82-4f69-8f6e-3322adfada49)

**Comment by JailedBird** [comment]
临时版本，试一下
com.github.JailedBird:ArouterKspCompiler:main-SNAPSHOT

**Comment by codejoyfun** [comment]
> 临时版本，试一下 com.github.JailedBird:ArouterKspCompiler:main-SNAPSHOT

验证通过了，赞

**Comment by JailedBird** [comment]
中午发布正式版本哈
