### ISSUE TITLE
jump到SecondActivtiy就闪退

### ISSUE THREAD

**Issue by danatechgithub4** [JailedBird/ArouterKspCompiler#14]
![image](https://github.com/JailedBird/ArouterKspCompiler/assets/127659297/4c7ea948-9f1c-4163-abb0-a7ef1a96651b)
你加这些干什么？故意的？用法都不对啊！

![image](https://github.com/JailedBird/ArouterKspCompiler/assets/127659297/50dc93eb-680f-4dbb-810b-1b4476048410)
这样用才对啊！

**Comment by JailedBird** [comment]
- 抱歉，app模块主要作用是Test case、而不是Sample示例；这是我的问题，没保证这个用例运行时正确，这可能对你造成了困扰； 
- 另外你注释的部分，主要是为了测试 复杂泛型、可空不可空、Type Alias等场景的 `@Autowired`的解析和生成；
- 如果你想了解原理请看compiler模块，你想查看和自测生成代码，请看 `app/build/generated/ksp` 的产物；如果你想观测增量编译请看README中的文档；
