### ISSUE TITLE
使用withStringArrayList在接收参数地方会出现One type argument expected for typealias ArrayList<E> = ArrayList<E>

### ISSUE THREAD

**Issue by fuxuanyang11** [JailedBird/ArouterKspCompiler#2]
如图 
![UK7TY %B_X121)V@{X2JK~1](https://user-images.githubusercontent.com/21265701/229722350-0a65976d-4ce1-42e5-aaa1-aba3d3548d2e.png)

**Comment by fuxuanyang11** [comment]
> 

![image](https://user-images.githubusercontent.com/21265701/230253516-67fb6016-2cbb-4d90-b443-74f65009eaf2.png)

**Comment by JailedBird** [comment]
你好, 初步诊断是ArrayList<T>在KSP中的一个解析问题,(可能和https://github.com/google/ksp/pull/182 issue有关), 建议这边先临时替换为mutableList<String>, ArrayList的问题我会持续跟踪和修复

**Comment by fuxuanyang11** [comment]
使用1.6.10-1.0.1-beta01版本没有问题了。有个问题：我ksp使用的版本是1.8.0-1.0.9，这个用1.6.10会有影响吗

**Comment by JailedBird** [comment]
> 

可能会(KSP本身存在bug), 我明天给你打包一个1.8.0版本的分支, 我先暂时关闭这个Issue了哈

**Comment by fuxuanyang11** [comment]
> 可能会(KSP本身存在bug), 我明天给你打包一个1.8.0版本的分支, 我先暂时关闭这个Issue了哈

👌，谢谢大佬

**Comment by JailedBird** [comment]
> > 可能会(KSP本身存在bug), 我明天给你打包一个1.8.0版本的分支, 我先暂时关闭这个Issue了哈
> 
> 👌，谢谢大佬

对应版本已发布， 请前往main分支README查看
