### ISSUE TITLE
[ksp] No providers found in processor classpath

### ISSUE THREAD

**Issue by tomKitty888888** [JailedBird/ArouterKspCompiler#7]
该有的配置都有，不知道还少什么 只要用ksp 引入就无法编译，博主有没有遇到
根部
plugins {
    id 'com.android.application' version '7.4.2' apply false
    id 'com.android.library' version '7.4.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.0' apply false
    id 'com.google.devtools.ksp' version '1.8.0-1.0.9' apply false
}
模块中
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
}

错误信息
> Task :app:kspDebugKotlin FAILED
e: [ksp] No providers found in processor classpath.
e: Error occurred in KSP, check log for detail

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kspDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by JailedBird** [comment]
没碰到过，看起来不是ArouterKspCompiler，而是你导入ksp插件导致的问题；
ksp插件的仓库加了么？
```
pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}
```

或者看下官方文档：
https://kotlinlang.org/docs/ksp-quickstart.html#use-your-own-processor-in-a-project

**Comment by tomKitty888888** [comment]
ok 感谢
