### ISSUE TITLE
ksp 最新版本

### ISSUE THREAD

**Issue by EdwinSmartBoy** [JailedBird/ArouterKspCompiler#9]
ksp最新版本能用吗

**Comment by JailedBird** [comment]
可，得等我明天我更新一个版本；

**Comment by JailedBird** [comment]
> ksp最新版本能用吗

已更新kotlin1.9.10 & ksp1.9.10-1.0.13 最新版本，详情参见master分支README文件；
![image](https://github.com/JailedBird/ArouterKspCompiler/assets/113177053/f5974cf9-aa85-42f1-a5ae-ab13a3ef5926)

![image](https://github.com/JailedBird/ArouterKspCompiler/assets/113177053/8da10013-161a-41ef-8127-3c170c4bb96e)

**Comment by EdwinSmartBoy** [comment]
非常感谢🙏，明天试试

**Comment by EdwinSmartBoy** [comment]
没办法获取到Autowired的参数，需要什么特殊处理吗？我已经按照wiki的加入的

**Comment by JailedBird** [comment]
> 没办法获取到Autowired的参数，需要什么特殊处理吗？我已经按照wiki的加入的

举个例子？或者看下这个？ https://github.com/JailedBird/ArouterKspCompiler/issues/4

**Comment by EdwinSmartBoy** [comment]
类似这种，但是我的数据类型是String，是获取不到的

**Comment by JailedBird** [comment]
请参考项目中示例（临时添加代码，截图展示）：
![image](https://github.com/JailedBird/ArouterKspCompiler/assets/113177053/e120a453-2c49-43fc-a9ff-b1c8c3b21002)

![image](https://github.com/JailedBird/ArouterKspCompiler/assets/113177053/2232c0ed-8618-4089-a6db-53406bc09b4f)

![image](https://github.com/JailedBird/ArouterKspCompiler/assets/113177053/1c758ef6-d31d-4d56-8612-7d4461f13f9d)

另：是否忘记注入 ARouter.getInstance().inject(this) ？
此外：如还是存在问题，请查看ksp生成文件是否正确？

![image](https://github.com/JailedBird/ArouterKspCompiler/assets/113177053/0dcc432a-14e6-4c56-a20c-1ac3933630d2)

**Comment by EdwinSmartBoy** [comment]
辛苦大佬，我排查一下

**Comment by JailedBird** [comment]
我暂时关闭问题了哈，后面有问题可以继续在这反馈；

**Comment by EdwinSmartBoy** [comment]
排查了一下，确实发现有个问题，如果使用了lateinit var进行标识的属性，就没法获取，去掉lateinit就能够，对应的ksp文件也是生成了的

**Comment by EdwinSmartBoy** [comment]
排查了一下，确实发现有个问题
如果使用了lateinit var进行标识的属性，就没法获取，提示变量未初始化
去掉lateinit就能够获取到注入的字段
对应的ksp文件也是生成了的

**Comment by JailedBird** [comment]
晚点试试，看看为啥；

**Comment by JailedBird** [comment]
错误原因：getString提前获取lateinit的值，作为默认值；
复现场景：使用lateinit 初始化String，必现；其他类型不会出现问题；

```
@Autowired
lateinit var lateStr: String
```

![image](https://github.com/JailedBird/ArouterKspCompiler/assets/113177053/33b9ecdf-81e2-441a-bc1b-cbf53a81a621)


解决方案：优化String初始化方式

![image](https://github.com/JailedBird/ArouterKspCompiler/assets/113177053/27682807-870c-4a32-b759-06fc0f6090af)

缺陷：
1、 唯一缺陷：不能主动为String传递null值；但是应该不会有人这么用；
优点：
1、 绕开对String判断Java/Kotlin的可空、不可空，因为判断可能会很复杂，且不准；

**Comment by JailedBird** [comment]
麻烦先用这个验证一下：
最新代码已提交到main分支，先用这个验证下；
com.github.JailedBird:ArouterKspCompiler:main-SNAPSHOT

**Comment by EdwinSmartBoy** [comment]
好的，麻烦您了

**Comment by EdwinSmartBoy** [comment]
测试了，可以使用

**Comment by JailedBird** [comment]
lateinit String bug已修复， xxx-1.0.5 已更新，参考README哈；

**Comment by EdwinSmartBoy** [comment]
好的，我试了com.github.JailedBird:ArouterKspCompiler:main-SNAPSHOT没啥问题，非常感谢！！
